#! /usr/bin/env bash

conda install --yes \
    -c conda-forge \
    "r-doParallel" \
    "r-foreach" \
    "r-gdalUtils" \
    "r-openssl" \
    "r-magick" \
    "r-raster" \
    "r-sf" \
    "r-readr" \
    "r-stringr" \
    "r-tidyr"

conda install -c conda-forge --strict-channel-priority r-arrow
conda install -c r r-jsonlite